---
title: "Medical Data Science Homework"
author: "Kira Wolff"
date: "29 12 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,  warning=FALSE, error=FALSE, message=FALSE)
# R code is never shown
# warnings, errors and messages are not included in pdf

```


```{r packages, include=FALSE}
library(tidyverse)
```

```{r data, include=FALSE}
cardio.dat <- read.csv("cardio_train.csv", sep=";") %>% 
  as_tibble() %>% 
  mutate(bmi = weight/(height/100)^2, #compute new variable bmi
         age.years = floor(age/365.25), # compute age in years
         # factor formatting
         cardio = factor(cardio,labels=c("disease absent", "disease present")), # change labels
         gender = factor(gender, labels = c("women", "men")),
         gluc = factor(gluc, labels =c("glucose normal", "above normal", "well above normal")),
         smoke = factor(smoke, labels = c("not smoking", "smoking")),
         alco = factor(alco, labels= c("not much alcohol intake", "much alcohol intake")),
         active = factor(active, labels=c("not very active", "very active")))

#check for unrealistic data of continuous parameters
cardio.dat %>% 
  summarize(min.age = min(age.years),
         max.age = max(age.years),
         min.height = min(height),
         max.height = max(height),
         min.weight = min(weight),
         max.weight = max(weight),
         min.sys = min(ap_hi),
         max.sys = max(ap_hi),
         min.dias = min(ap_lo),
         max.dias = max(ap_lo)
         )

```

## Exercise 1

BMI ~ Cardio, no filter

```{r bmi vergleich}
bmi.tab <- cardio.dat %>% 
              group_by(cardio) %>% 
              summarize(mean = round(mean(bmi, na.rm=T),2),
                        sd = round(sd(bmi, na.rm=T),2))

knitr::kable(bmi.tab, 
             caption= "BMI by cardiovascular disease")
```

## Exercise 2

Systolic blood pressure, no filter

```{r}
cardio.dat %>% 
  summarize(cor=cor(ap_hi, bmi))


cardio.dat %>% 
  group_by(cardio) %>% 
  summarize(cor=cor(ap_hi, bmi))

cardio.dat %>% 
  ggplot(aes(ap_hi, bmi))+
    geom_point()
```
## Exercise 3

Diastolic blood pressure, no filter

```{r}
cardio.dat %>% 
  summarize(cor=cor(ap_lo, bmi))


cardio.dat %>% 
  group_by(cardio) %>% 
  summarize(cor=cor(ap_lo, bmi))
```
## Exercise 4

```{r quantiles}
sys.95 <- cardio.dat %>% 
            summarize(q = quantile(ap_hi, prob=0.95, na.rm=T))

dias.95 <- cardio.dat %>% 
            summarize(q =quantile(ap_lo, prob=0.95, na.rm=T))

bmi.95 <- cardio.dat %>% 
            summarize(q =quantile(bmi, prob=0.95, na.rm=T))

cardio.dat.filter <- cardio.dat %>% 
                  filter(bmi < bmi.95$q,
                         ap_hi < sys.95$q,
                         ap_lo < dias.95$q)
```


BMI ~ Cardio, blood pressure and bmi filter

```{r bmi vergleich filterd}
bmi.tab.filter <- cardio.dat.filter %>% 
              group_by(cardio) %>% 
              summarize(mean = round(mean(bmi, na.rm=T),2),
                        sd = round(sd(bmi, na.rm=T),2))

knitr::kable(bmi.tab.filter, 
             caption= "BMI by cardiovascular disease")
```


Systolic blood pressure, blood pressure and bmi filter

```{r}
cardio.dat.filter %>% 
  summarize(cor=cor(ap_hi, bmi))


cardio.dat.filter %>% 
  group_by(cardio) %>% 
  summarize(cor=cor(ap_hi, bmi))
```


Diastolic blood pressure, blood pressure and bmi filter

```{r}
cardio.dat.filter %>% 
  summarize(cor=cor(ap_lo, bmi))


cardio.dat.filter %>% 
  group_by(cardio) %>% 
  summarize(cor=cor(ap_lo, bmi))
```

## Exercise 5

```{r}
cardio.dat %>% 
  ggplot(aes(age.years, ..density..))+
    geom_histogram()+
    facet_grid(~cardio)+
    theme_minimal()
```
## Exercise 6

```{r}
cardio.dat %>% 
  ggplot(aes(age.years, ..density.., fill=gender, group=gender))+
    geom_histogram()+
    facet_grid(~cardio)+
    theme_minimal()

cardio.dat %>% 
  ggplot(aes(age.years, ..density.., fill=gender, group=gender))+
    geom_histogram()+
    facet_grid(gender~cardio)+
    theme_minimal()
```
## Exercise 7
```{r}
cardio.dat %>% 
  ggplot(aes(age.years, ..density.., fill=gender, group=gender))+
    geom_histogram()+
    facet_grid(gluc~cardio)+
    theme_minimal()
```
Mittelwert und Median einzeichnen?

```{r}
cardio.dat %>% 
  group_by(cardio) %>% 
  summarise(alcohol = table(alco),
            smoking = table(smoke),
            activity = table(active))

cardio.dat %>% 
  group_by(cardio) %>% 
  summarise(alcohol = table(alco),
            smoking = table(smoke),
            activity = table(active))
```

```{r chi²}
#cardio.dat %>% 
  #table(cardio, alco)

chisq.test(table(cardio.dat$cardio, cardio.dat$alco))
chisq.test(table(cardio.dat$alco,cardio.dat$cardio))

chisq.test(table(cardio.dat$cardio, cardio.dat$smoke))

chisq.test(table(cardio.dat$cardio, cardio.dat$active))


```